export const FETCH_MESSAGES_START = "FETCH_MESSAGES_START";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILED = "FETCH_MESSAGES_FAILED";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const SELECT_CONVERSATION = "SELECT_CONVERSATION";
