export const FETCH_MEMBERS_START = "FETCH_MEMBERS_START";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_FAILED = "FETCH_MEMBERS_FAILED";
export const CREATE_CONVERSATION = "CREATE_CONVERSATION";

export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
