export const FETCH_LOGIN_START = "FETCH_LOGIN_START";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILED = "FETCH_LOGIN_FAILED";
export const ADD_CONTACT = "ADD_CONTACT";
export const SET_MESSAGE = "SET_MESSAGE";
export const LOG_OUT = "LOG_OUT";
